version: "2"

linters:
  disable:
    - gocyclo
    - errcheck
    - dupl
  settings:
    revive:
      rules:
        - name: exported
          severity: warning
          disabled: false

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
      - path-except: _test\.go
        linters:
          - forbidigo
    paths-except:
      - bin
      - vendor

formatters:
  enable:
    - gofumpt
    - goimports
    - golines
  settings:
    goimports:
      local-prefixes:
        - github.com/shrik450/dijester

run:
  timeout: 5m
