linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - revive

linters-settings:
  gofmt:
    simplify: true
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
  goimports:
    local-prefixes: github.com/shrik450/dijester

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  exclude-dirs:
    - bin
    - vendor

run:
  timeout: 5m

service:
  golangci-lint-version: 1.64.x