[package]
name = "dijester"
version = "0.1.0"
edition = "2021"
authors = ["Shrikanth Upadhayaya <shrik450@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
