# Example Dijester Configuration

[digest]
format = "markdown"
output_path = "./my_digest.md"
title = "My Daily News Digest"

[global]
concurrent_fetches = 3
timeout = "30s"
user_agent = "Dijester/1.0"

[sources.hackernews]
enabled = true
max_articles = 5
type = "hackernews"

[sources.hackernews.options]
categories = ["front_page"]
min_score = 100
