# Example Dijester Configuration

[digest]
format = "epub"
output_path = "./my_digest.epub"
title = "My Daily News Digest"

[global]
concurrent_fetches = 3
timeout = "30s"
user_agent = "Dijester/1.0"

[sources.hackernews]
enabled = true
max_articles = 10
type = "hackernews"

[sources.hackernews.options]
categories = ["front_page"]
include_metadata = true
min_score = 100

[sources.nytimes]
enabled = true
max_articles = 5
name = "New York Times"
type = "rss"

[sources.nytimes.options]
include_summary = true
url = "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml"

[global_processors]
processors = ["readability"]
