# Example Dijester Configuration

[digest]
format = "markdown"
output_path = "./digest-{{.Year}}-{{.MonthNum}}-{{.Day}}.md"
title = "My Daily News Digest - {{.Date}}"
dedup_by_url = true
sort_by = ["PublishedAt:desc", "Title:asc"]

[global]
concurrent_fetches = 3
timeout = "30s"
user_agent = "Dijester/1.0"

[sources.hackernews]
enabled = true
max_articles = 5
type = "hackernews"
word_denylist = ["crypto", "NFT", "blockchain"]

[sources.hackernews.options]
categories = ["front_page"]
min_score = 100
