# Example Dijester Configuration

[digest]
dedup_by_url = true
format = "epub"
output_path = "{{.DTLong}}.epub"
sort_by = ["SourceName", "PublishedAt:desc"]
title = "Daily Digest for {{.Date}}"

[global]
concurrent_fetches = 3
timeout = "30s"

[sources.hackernews]
enabled = true
type = "hackernews"
word_denylist = ["crypto", "NFT", "blockchain"]

[sources.hackernews.options]
max_articles = 10
page = "past"
show_dead = true

[sources.ars_technica]
enabled = true
type = "rss"
word_denylist = ["deal"]

[sources.ars_technica.options]
fetch_full_articles = true
url = "https://feeds.arstechnica.com/arstechnica/index"

[global_processors]
processors = ["readability", "sanitizer"]

[formatting]
include_metadata = true
store_images = true
