# Example Dijester Configuration

[digest]
format = "epub"
output_path = "hn-{{.DTLong}}.epub"
title = "Hacker News Digest for {{.Date}}"

[global]
concurrent_fetches = 3
timeout = "30s"
user_agent = "Dijester/1.0"

[sources.hackernews]
enabled = true
type = "hackernews"

[sources.hackernews.options]
max_articles = 10
min_score = 10
page = "past"
show_dead = true

[global_processors]
processors = ["readability", "sanitizer"]

[formatting]
include_metadata = true
store_images = true
