# Example Dijester Configuration

[digest]
title = "My Daily News Digest"
format = "epub"
output_path = "./my_digest.epub"

[global]
concurrent_fetches = 3
user_agent = "Dijester/1.0"
timeout = "30s"

[sources.hackernews]
type = "hackernews"
enabled = true
max_articles = 10

[sources.hackernews.options]
min_score = 100
categories = ["front_page"]

[sources.nytimes]
type = "rss"
name = "New York Times"
enabled = true
max_articles = 5

[sources.nytimes.options]
url = "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml"
include_summary = true