name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Install tools
        run: make tools

      - name: Check Format, Lint, and Test
        run: make ci-check

      - name: Build
        run: make build

      - name: End-to-end Tests
        run: make e2e-test
