name: PR Checks

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Output paths to cache for deps
        run: |
          echo "GO_CACHE_PATH=$(go env GOCACHE)" >> $GITHUB_ENV
          echo "GO_MODCACHE_PATH=$(go env GOMODCACHE)" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.GO_CACHE_PATH }}
            ${{ env.GO_MODCACHE_PATH }}
          key: ${{ runner.os }}-gocache-${{ hashFiles('go.mod') }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7

      - name: Build
        run: make build

      - name: Run unit tests
        run: make test

      - name: End-to-end Tests
        run: make e2e-test
